# Tensores

Un tensor es como un array de Numpy, pero con soporte para GPU y gradientes.+
Los tensores son la unidad mínima de datos en deep learning.
Todo modelo se reduce a operaciones tensoriales (suma, multiplicación, activación).
Forward pass = aplicar una serie de transformaciones determinísticas sobre tensores.

requires_grad=True activa el seguimiento para el backprop posterior.

In [4]:
#SETUP
import torch

#Seed para reproducibilidad, los pesos y biases son aleatorios
#pero queremos que sean los mismos en cada run
torch.manual_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Usando:", device)
torch.cuda.get_device_name(0)
print(torch.cuda.memory_summary(device=None, abbreviated=True))



Usando: cuda
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Active memory         |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Requested memory      |      0 B   |      0 B   |      0 B   |      0 B   |
|--------------------------------------------------

In [ ]:
# Declaramos tensores de entrada, pesos y bias en GPU.
# Esto representa el núcleo matemático de una sola neurona (perceptrón lineal).

# x tiene forma (3, 2):
#   - 3 filas → 3 casas (3 muestras)
#   - 2 columnas → 2 características por casa (tamaño, nº de habitaciones)
# Estos datos vendrian de un dataset de casas.
x = torch.tensor([
    [90.0, 3.0],   # Casa 1
    [120.0, 4.0],  # Casa 2
    [60.0, 2.0]    # Casa 3
], device="cuda")

# w tiene forma (2, 1):
#   - 2 filas → un peso por cada característica de entrada
#   - 1 columna → una neurona (una salida)
# Supongamos que el tamaño influye más que el número de habitaciones.
# Estos pesos serian random, pero los fijamos para el ejemplo.
w = torch.tensor([
    [0.8],  # peso asociado al tamaño
    [0.3]   # peso asociado a las habitaciones
], device="cuda")

# b tiene forma (1,):
#   - un sesgo que ajusta la salida de todas las muestras.
b = torch.tensor([10.0], device="cuda")

# operación lineal: y = x @ w + b
#   - @ es el producto matricial
#   - El bias se suma a cada fila del resultado
y = x @ w + b

print("=== Datos de entrada (x) ===")
print(x)
print("\n=== Pesos (w) ===")
print(w)
print("\n=== Bias (b) ===")
print(b)
print("\n=== Salida (y = x @ w + b) ===")
print(y)

=== Datos de entrada (x) ===
tensor([[ 90.,   3.],
        [120.,   4.],
        [ 60.,   2.]], device='cuda:0')

=== Pesos (w) ===
tensor([[0.8000],
        [0.3000]], device='cuda:0')

=== Bias (b) ===
tensor([10.], device='cuda:0')

=== Salida (y = x @ w + b) ===
tensor([[ 82.9000],
        [107.2000],
        [ 58.6000]], device='cuda:0')
